services:
  - type: web
    name: multi-agent-rag
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: DATABASE_URL
        value: postgres://your_user:your_pass@your_host:5432/your_db
